apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnist-classifier-service
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: mnist-classifier-service
  template:
    metadata:
      labels:
        app: mnist-classifier-service
    spec:
      containers:
      - name: mnist-classifier-container
        image: mhrahman7105/mnist-classifier-service:v1
        ports:
        - containerPort: 5000
        env:
        - name: MNIST_FLASK_APP
          value: "app.py"
---
apiVersion: v1
kind: Service
metadata:
  name: mnist-classifier-service
spec:
  selector:
    app: mnist-classifier-service
  ports:
  - protocol: TCP
    port: 80      # Port exposed by the service
    targetPort: 5000  # Port the app container listens on
  type: LoadBalancer  # Use LoadBalancer for external access (can change to ClusterIP for internal access only)
